# Generated by Django 5.2.1 on 2025-07-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedtext",
            old_name="exercise_id",
            new_name="exercise",
        ),
    ]
