# Generated by Django 5.1.6 on 2025-02-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtext',
            name='created_at',
        ),
    ]
