# Generated by Django 5.1.6 on 2025-03-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0002_remove_savedtext_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor_position', models.IntegerField()),
                ('paragraph_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
