# Generated by Django 5.2.1 on 2025-07-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0003_savedtext_student_alter_savedtext_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="typingevent",
            name="saved_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_analysis.savedtext",
            ),
        ),
    ]
