# Generated by Django 5.1.6 on 2025-03-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0004_usertyping_delete_typingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtext',
            name='list_position',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedtext',
            name='list_progression',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
