# Generated by Django 5.2.1 on 2025-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0004_typingevent_saved_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typingevent",
            name="timestamp",
            field=models.FloatField(),
        ),
    ]
