# Generated by Django 5.2.1 on 2025-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0005_alter_typingevent_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_approach", models.TextField()),
                ("changes", models.TextField()),
                ("clarity", models.CharField(max_length=10)),
                ("organization", models.CharField(max_length=10)),
                ("grammar", models.CharField(max_length=10)),
                ("style", models.CharField(max_length=10)),
                ("time_use", models.TextField()),
                ("revision_continous", models.TextField()),
                ("revision_improvements", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
