# Generated by Django 5.1.6 on 2025-03-16 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0005_savedtext_list_position_savedtext_list_progression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtext',
            name='score',
        ),
        migrations.AddField(
            model_name='savedtext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedtext',
            name='list_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savedtext',
            name='list_progression',
            field=models.TextField(blank=True),
        ),
    ]
