# Generated by Django 5.2.1 on 2025-08-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0006_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="saved_text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="text_analysis.savedtext",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedtext",
            name="report_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
