# Generated by Django 5.2.1 on 2025-08-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0007_questionnaire_saved_text_savedtext_report_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="saved_text",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires",
                to="text_analysis.savedtext",
            ),
        ),
    ]
