# Generated by Django 5.1.6 on 2025-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0007_rename_saved_text_usertyping_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertyping',
            name='cursor_position',
            field=models.IntegerField(default=0),
        ),
    ]
