# Generated by Django 5.2.1 on 2025-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0008_alter_questionnaire_saved_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedannotation",
            old_name="student",
            new_name="teacher",
        ),
        migrations.AddField(
            model_name="savedtext",
            name="n_annotated",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savedannotation",
            name="annotation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
