# Generated by Django 5.2.1 on 2025-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0009_rename_student_savedannotation_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="session",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="savedtext",
            name="session",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
