# Generated by Django 5.1.6 on 2025-03-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0009_typingevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertyping',
            old_name='text',
            new_name='text_progression',
        ),
        migrations.AddField(
            model_name='usertyping',
            name='session_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertyping',
            name='cursor_position',
            field=models.IntegerField(),
        ),
    ]
