# Generated by Django 5.2.1 on 2025-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0010_exercise_session_savedtext_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedtext",
            name="feedback_opened",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
