# Generated by Django 5.2.1 on 2025-08-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_analysis", "0011_savedtext_feedback_opened"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireFeeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_feeling", models.TextField()),
                ("specific_feedback", models.TextField()),
                ("efforts", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saved_text",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_feeling",
                        to="text_analysis.savedtext",
                    ),
                ),
            ],
        ),
    ]
