# Generated by Django 5.0.1 on 2025-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analysis', '0013_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='xml_content',
        ),
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=models.TextField(default='', help_text='Entrez votre énoncé de l’exercice'),
        ),
    ]
