# Generated by Django 5.2.1 on 2025-08-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_n_annotated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="group",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
