# Generated by Django 5.2.1 on 2025-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="session",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
