# Generated by Django 5.2.1 on 2025-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="feedback_ready",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="feedback_seen",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
